namespace AttendanceManager.Domain.Common
{
    public static class Constants
    {
        public static readonly string Claim_Name_Email = "email";
        public static readonly string Claim_Name_Name = "name";
        public static readonly string Claim_Name_Code = "code";
        public static readonly string Claim_Name_Role = "role";
        public static readonly string Subject = "AttendanceManager Credentials";
        public static readonly string Body = "Hello {0}! <br><br> Your account was created using those credentials:<br><br> <strong>Email:</strong>{1} <br> <strong>Password:</strong>{2} <br><br> <strong>This email was autogenerated, please do not replay!</strong>";
        public static readonly string CharsString = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        public static readonly int PasswordLength = 8;
        public static readonly int AttendanceCodeLength = 6;
        public static readonly int RefreshTokenLength = 64;
        public static readonly string DateFormat = "dddd, yyyy MMMM dd HH:mm";
        public static readonly string ShortDateFormat = "yyyy-MM-dd HH:mm";
        public static readonly string CustomBonusPointsImage = "custom_bonus_points.jpg";
        public static readonly string CustomAttendanceImage = "custom_attendances.jpg";
        public static readonly string CustomAttendanceDescription = "Achieve this bagde by having {0} attendances at {1}.";
        public static readonly string CustomBonusPointsDescription = "Achieve this bagde by having {0} bonus points at {1}.";
    }

    public static class ErrorMessages
    {
        public static readonly string AlreadyExists_CollaboratorInsert_Error = "The teacher is already a member of this document!";
        public static readonly string AlreadyExists_BadgeInsert_Error = "There is already a badge defined for this activity, you can't add more!";

        public static readonly string BadRequest_CollaboratorInsert_Error = "You can add only teachers as collaborators! This user ({0}) is a student.";
        public readonly static string BadRequest_UnauthorizedError = "Only teachers can access this data!";
        public readonly static string BadRequest_InvalidParameters_EmailCollection_Error = "Invalid parameters: you cannot pass email and collection id in the same time!";
        public readonly static string BadRequest_InvalidParameters_Collaborator_Error = "Invalid parameters: you cannot be a collaborator because you own this report!";
        public readonly static string BadRequest_ParametersMissing_Error = "Invalid parameters: some required parameters are missing! Check the API documentation.";
        public readonly static string BadRequest_InvalidParameters_BooleanParams_Error = "Invalid parameters: email cannot be shown!";
        public readonly static string BadRequest_InvalidParameters_ConversionFaild_Error = "Invalid parameters: conversion faild!";
        public readonly static string BadRequest_CreateCollectionParams_Error = "Activity time and type are required.";
        public readonly static string BadRequest_CreateCollectionParams2_Error = "Invalid activity time format. Expected format: yyyy-MM-dd HH:mm";
        public readonly static string BadRequest_CreateCollectionParams3_Error = "Invalid type format. Expected format: 'Lecture', 'Laboratory' or 'Seminary'";

        public readonly static string Info_LogError = "An error occures when we try to call {0}.";
        public readonly static string MessageReceived_LogError = "Message received: {0}";
        public readonly static string InnerMessageReceived_LogError = "Inner exception received: {0}";
        public static readonly string NoContentReportBaseMessage = "Something went wrong and the current report couldn't be loaded! Reload the page.";


        public readonly static string SomethingWentWrong_NotificationDelete_Error = "Something went wrong and the notification wasn't been deleted. Please try again!";
        public readonly static string SomethingWentWrong_NotificationUpdate_Error = "Something went wrong and the notification wasn't been set as read. Please try again!";
        public readonly static string SomethingWentWrong_NotificationInsert_Error = "Something went wrong when the notification was sent. The user(s) wasn't(weren't) informed about your changes.";
        public readonly static string SomethingWentWrong_CreateReportNotificationInsert_Error = "Something went wrong and the notifications weren't sent, but the document was successfully created. The users weren't informed about this new report.";
        public readonly static string SomethingWentWrong_CollectionsNotAvailableError = "Something went wrong and no collection was found for this report. Try again later!";
        public static readonly string SomethingWentWrongGenericMessage = "Something went wrong when the command was executed! See log files for more details or try again.";
        public static readonly string SomethingWentWrongBadgesGenericMessage = "Something went wrong during the rewards process! See log files for more details or try again.";
        public static readonly string SomethingWentWrongNotificationsGenericMessage = "Something went wrong during the notification process! See log files for more details or try again.";
        public static readonly string SomethingWentWrongInserAttendancesMessage = "Something went wrong when the involvements was added! See log files to more details or try again.";
        public static readonly string SomethingWentWrongInsertBadgeMessage = "Something went wrong when the rewards was added. See the log files for more details!";
        public static readonly string SomethingWentWrongEmailSendMessage = "Something went wrong and the user will not receive any email, but the account was created. Please contact him and give him the credentials.";
    }

    public static class NotificationMessages
    {
        public readonly static string CustomBadgeAddedNotification = "A new badge called <i>{0}</i> was added in <i>{1}</i> report. Check out the report to see what you need to do to achieve this badge!";
        public readonly static string CollaboratorAddedNotification = "<i>{0}</i> was added you as collaborator to the report called <i>{1}</i>.";
        public readonly static string AchievedBadgeNotification = "You achived <i>{0}</i> at <i>{1}</i>.";
        public readonly static string CreateReportNotification = "You are now member of report <i>{0}</i>. This report was created by <i>{1}</i> on <i>{2}</i>.";
        public readonly static string CreateCollectionNotification = "<i>{0}</i> added a new collection into the report <i>{1}</i>. Be careful in case that you need to be present or not.";
    }
}
